### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Bluscream** [TheUnknownNO/TruckersMP-Launcher#7]
This always happens when I click on Settings
![image](https://cloud.githubusercontent.com/assets/3318223/21624091/caba9b10-d205-11e6-90db-7a704b05b8bf.png)
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at truckersmplauncher.Settings..ctor()
   at truckersmplauncher.Main.Settings_btn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
truckersmplauncher
    Assembly Version: 1.3.3.7
    Win32 Version: 1.3.3.7
    CodeBase: file:///E:/Steam/steamapps/common/Euro%20Truck%20Simulator%202/TMPLauncher.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 4.5.0.0
    Win32 Version: 1.3.3.7
    CodeBase: file:///E:/Steam/steamapps/common/Euro%20Truck%20Simulator%202/TMPLauncher.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by thomasakarlsen** [comment]
I have a feeling I know what causes this error, I'll investigate the bug further and release a fix for the next update!

**Comment by thomasakarlsen** [comment]
I have reason to belive this issue is related to the ETS2/ATS Configuration editor part of the settings dialog. I will have it fixed for the next update to stop it from crashing.

Quick question, have you changed your game "home path" (where the game stores your profiles, etc)?

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/21767737/0f33f40c-d676-11e6-8b00-af2eba311cdc.png)
yes :D

**Comment by Bluscream** [comment]
but I have it hardlinked to Documents
![image](https://cloud.githubusercontent.com/assets/3318223/21767882/d80dca88-d676-11e6-962f-e61e51993f4e.png)

**Comment by Bluscream** [comment]
Some more info for you ♥
![image](https://cloud.githubusercontent.com/assets/3318223/21768720/6b99cce4-d67b-11e6-9823-3ffaba71bc47.png)

**Comment by Bluscream** [comment]
OK, now it works. The problem was that I did not hardlink my ATS homedir to Documents

https://github.com/TruckerMP/TruckersMP-Launcher/commit/810da580049f2a43f451d3c65777191fdb5496cc#diff-46639b9ab78dbf6f7a83556dbf380cefR179

**Comment by thomasakarlsen** [comment]
Yeah, was about to say. I will to some changes however to make sure it doesnt try to load files which do not exists as thats what the issue here was.

**Comment by Bluscream** [comment]
You should also try catch the radio stream cause when it fails the app crashes

**Comment by Bluscream** [comment]
Any news on this whole thing?

**Comment by thomasakarlsen** [comment]
As I've said earlier progress is slow due to real life, and other projects that have taken priority.
